### ISSUE TITLE
How to use functions correctly?

### ISSUE THREAD

**Issue by Madrox24** [dclelland/LIFXClient#1]
Hi, your project looks very interesting, but unfortunately I don't understand how to use it. Every time calling the function from your API (e.g. _client.light.setColor()_) do I need to use _LIFXClient.connect()_? Or maybe just use the connect function only once?
`LIFXClient.connect(host: .ipv4(IPv4Address("192.168.1.4")!)).then { client in
    return client.light.setColor(color: .orange)
}`

I also don't quite know how to get for example _client.light.getPower()_ properties.
Sorry if the questions are trivial, but I would like to understand how to use your library.
Thank you for help.

**Comment by dclelland** [comment]
Hi, yeap you'll need to connect to the light first before sending messages to it.

It might be useful to get familiar with [PromiseKit](https://github.com/mxcl/PromiseKit) if you have not used it before.

These operations can be chained together, or you can make the connection first and then send messages to it later.

I've just open-sourced the mac app I've been building, perhaps have a read and see if it makes sense: https://github.com/dclelland/3LED/blob/master/3LED/AppDelegate.swift

**Comment by dclelland** [comment]
In this app, the AppDelegate fetches a list of connections and then stores them in the `NSMenuItem.representedObject` properties. When a menu item is selected, the connection is retrieved from the menu item and passed to a window, which can then call `client.light.setColor` etc without first having to create a new connection.

Hope this helps... let me know if you have any more questions.

**Comment by Madrox24** [comment]
Thank you so much, I managed to deal with it! Your library helps me a lot in my iOS project :).
